
// This file is auto-generated by a script. Do not modify manually.
import { icons } from './icons';
import Icon, {type IconProps} from './icon';


const DashboardIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'Dashboard');
    if (!icon) {
        console.error('Icon "Dashboard" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
DashboardIcon.displayName = 'DashboardIcon';
export { DashboardIcon };



const ArrowDropDownIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'ArrowDropDown');
    if (!icon) {
        console.error('Icon "ArrowDropDown" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
ArrowDropDownIcon.displayName = 'ArrowDropDownIcon';
export { ArrowDropDownIcon };



const ArrowLeftIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'ArrowLeft');
    if (!icon) {
        console.error('Icon "ArrowLeft" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
ArrowLeftIcon.displayName = 'ArrowLeftIcon';
export { ArrowLeftIcon };



const DiamondIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'Diamond');
    if (!icon) {
        console.error('Icon "Diamond" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
DiamondIcon.displayName = 'DiamondIcon';
export { DiamondIcon };



const GraphIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'Graph');
    if (!icon) {
        console.error('Icon "Graph" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
GraphIcon.displayName = 'GraphIcon';
export { GraphIcon };



const MailIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'Mail');
    if (!icon) {
        console.error('Icon "Mail" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
MailIcon.displayName = 'MailIcon';
export { MailIcon };



const PieChartIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'PieChart');
    if (!icon) {
        console.error('Icon "PieChart" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
PieChartIcon.displayName = 'PieChartIcon';
export { PieChartIcon };



const TubeIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'Tube');
    if (!icon) {
        console.error('Icon "Tube" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
TubeIcon.displayName = 'TubeIcon';
export { TubeIcon };



const EditIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'Edit');
    if (!icon) {
        console.error('Icon "Edit" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
EditIcon.displayName = 'EditIcon';
export { EditIcon };



const LaptopIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'Laptop');
    if (!icon) {
        console.error('Icon "Laptop" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
LaptopIcon.displayName = 'LaptopIcon';
export { LaptopIcon };



const DesktopIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'Desktop');
    if (!icon) {
        console.error('Icon "Desktop" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
DesktopIcon.displayName = 'DesktopIcon';
export { DesktopIcon };



const PagesIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'Pages');
    if (!icon) {
        console.error('Icon "Pages" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
PagesIcon.displayName = 'PagesIcon';
export { PagesIcon };



const WorldIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'World');
    if (!icon) {
        console.error('Icon "World" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
WorldIcon.displayName = 'WorldIcon';
export { WorldIcon };



const BurgerMenuIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'BurgerMenu');
    if (!icon) {
        console.error('Icon "BurgerMenu" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
BurgerMenuIcon.displayName = 'BurgerMenuIcon';
export { BurgerMenuIcon };



const BellIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'Bell');
    if (!icon) {
        console.error('Icon "Bell" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
BellIcon.displayName = 'BellIcon';
export { BellIcon };



const LogoutIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'Logout');
    if (!icon) {
        console.error('Icon "Logout" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
LogoutIcon.displayName = 'LogoutIcon';
export { LogoutIcon };



const InboxIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'Inbox');
    if (!icon) {
        console.error('Icon "Inbox" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
InboxIcon.displayName = 'InboxIcon';
export { InboxIcon };



const SunIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'Sun');
    if (!icon) {
        console.error('Icon "Sun" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
SunIcon.displayName = 'SunIcon';
export { SunIcon };



const DescriptionIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'Description');
    if (!icon) {
        console.error('Icon "Description" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
DescriptionIcon.displayName = 'DescriptionIcon';
export { DescriptionIcon };



const TrashIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'Trash');
    if (!icon) {
        console.error('Icon "Trash" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
TrashIcon.displayName = 'TrashIcon';
export { TrashIcon };



const OfferIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'Offer');
    if (!icon) {
        console.error('Icon "Offer" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
OfferIcon.displayName = 'OfferIcon';
export { OfferIcon };



const RefreshIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'Refresh');
    if (!icon) {
        console.error('Icon "Refresh" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
RefreshIcon.displayName = 'RefreshIcon';
export { RefreshIcon };



const EyeIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'Eye');
    if (!icon) {
        console.error('Icon "Eye" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
EyeIcon.displayName = 'EyeIcon';
export { EyeIcon };



const ExclamationMarkIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'ExclamationMark');
    if (!icon) {
        console.error('Icon "ExclamationMark" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
ExclamationMarkIcon.displayName = 'ExclamationMarkIcon';
export { ExclamationMarkIcon };



const LeftArrowIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'LeftArrow');
    if (!icon) {
        console.error('Icon "LeftArrow" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
LeftArrowIcon.displayName = 'LeftArrowIcon';
export { LeftArrowIcon };



const RightArrowIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'RightArrow');
    if (!icon) {
        console.error('Icon "RightArrow" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
RightArrowIcon.displayName = 'RightArrowIcon';
export { RightArrowIcon };



const GearsIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'Gears');
    if (!icon) {
        console.error('Icon "Gears" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
GearsIcon.displayName = 'GearsIcon';
export { GearsIcon };



const AttachmentIcon = (props: IconProps) => {
    const icon = icons.find(icon => icon.name === 'Attachment');
    if (!icon) {
        console.error('Icon "Attachment" not found in icons array.');
        return null;
    }
    return <Icon path={icon.path} viewBox={icon.viewBox} {...props} />;
};
    
AttachmentIcon.displayName = 'AttachmentIcon';
export { AttachmentIcon };

